# config.toml
# This is a config TOML document

title = "TOML config"

[commit]
minimum_length = 7
maximum_length = 50
allowed_capitalize = false
required_spaces = true
show_clean = true
show_warning = true

[component]
[component.emoji]
allowed = true
required = true
any_values = false

[component.type]
allowed = false
required = false
any_values = false

[component.scope]
allowed = true
required = true
any_values = false


[types]
BREAKING = [':boom:', 'ğŸ’¥']
feat = [':sparkles:', 'âœ¨']
fix = [':ladybird:', 'ğŸ']
refactor = [':recycle:', 'â™»ï¸']
chore = [':gear:', 'âš™ï¸']

[scopes]
values = ["api", "web", "app"]
