# config.toml
# This is a config TOML document

title = "TOML config"

[component]
[component.emoji]
allowed = true
required = true
any_values = true

[component.type]
allowed = true
required = true
any_values = true

[component.scope]
allowed = true
required = true
any_values = true

[component.message]
allowed = true
required = true
any_values = true

[types]
BREAKING = [':boom:', 'ğŸ’¥']
feat = [':sparkles:', 'âœ¨']
fix = [':ladybird:', 'ğŸ']
refactor = [':recycle:', 'â™»ï¸']
chore = [':gear:', 'âš™ï¸']

[scopes]
values = ["api", "web", "app"]
