# config.toml
# This is a config TOML document

title = "TOML config"

[commit]
minimum_length = 7
maximum_length = 50
allowed_capitalize = false
show_clean = true
show_warning = true

[component]
[component.emoji]
allowed = true
required = true
any_values = false
required_end_spaces = true

[component.type]
allowed = false
required = false
any_values = false
required_end_spaces = true
split_delimiter = ":"

[component.scope]
allowed = true
required = true
any_values = false
required_spaces = true
start_delimiter = "("
end_delimiter = ")"


[types]
BREAKING = [':boom:', 'ğŸ’¥']
feat = [':sparkles:', 'âœ¨']
fix = [':ladybird:', 'ğŸ']
refactor = [':recycle:', 'â™»ï¸']
chore = [':gear:', 'âš™ï¸']

[scopes]
values = ["api", "web", "app"]
